version: "3.3"
services: 
    web-app:
        container_name: "angular_basic"
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
            - "4020:4020"
        networks:
            default:
                ipv4_address:  172.18.0.7
        restart: always

networks:
  default:
    external:
      name: docker-network